<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeviceDNA.Model\DeviceDNA.Model.csproj" />
    <ProjectReference Include="..\DeviceDNA.Application\DeviceDNA.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
