<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeviceDNA.Model\DeviceDNA.Model.csproj" />
    <ProjectReference Include="..\DeviceDNA.PlatformAdapters\DeviceDNA.PlatformAdapters.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
